source:
  base_url: "https://storage.googleapis.com/osv-vulnerabilities"
  index_url: "https://storage.googleapis.com/osv-vulnerabilities/index.html"
  all_zip_url: "https://storage.googleapis.com/osv-vulnerabilities/all.zip"

storage:
  data_dir: "data"
  logs_dir: "logs"

recording:
  file_path: "logs/sync_history.csv"

sync:
  timeout: 3000
  retry_attempts: 3

browser:
  browser_type: "chromium"  # firefox, webkit, chromium
  headless: true
  timeout: 30000
  viewport:
    width: 1280
    height: 800
  options:
    args: ["--disable-gpu", "--no-sandbox"] 